#ifndef _TGMATH_H
#define _TGMATH_H

#include <complex.h>
#include <math.h>

#define __TGMATH_3(fn, ...) __builtin_tgmath(fn##f, fn, fn##l, __VA_ARGS__)
#define __TGMATH_6(fn, ...) __builtin_tgmath(fn##f, fn, fn##l, c##fn##f, c##fn, c##fn##l, __VA_ARGS__)

#define acos(z) __TGMATH_6(acos, (z))
#define asin(z) __TGMATH_6(asin, (z))
#define atan(z) __TGMATH_6(atan, (z))
#define acosh(z) __TGMATH_6(acosh, (z))
#define asinh(z) __TGMATH_6(asinh, (z))
#define atanh(z) __TGMATH_6(atanh, (z))
#define cos(z) __TGMATH_6(cos, (z))
#define sin(z) __TGMATH_6(sin, (z))
#define tan(z) __TGMATH_6(tan, (z))
#define cosh(z) __TGMATH_6(cosh, (z))
#define sinh(z) __TGMATH_6(sinh, (z))
#define tanh(z) __TGMATH_6(tanh, (z))
#define exp(z) __TGMATH_6(exp, (z))
#define log(z) __TGMATH_6(log, (z))
#define pow(x, y) __TGMATH_6(pow, (x), (y))
#define sqrt(z) __TGMATH_6(sqrt, (z))
#define fabs(z) __builtin_tgmath(fabsf, fabs, fabsl, cabsf, cabs, cabsl, (z))

#define atan2(y, x) __TGMATH_3(atan2, (y), (x))
#define cbrt(x) __TGMATH_3(cbrt, (x))
#define ceil(x) __TGMATH_3(ceil, (x))
#define copysign(x, y) __TGMATH_3(copysign, (x), (y))
#define erf(x) __TGMATH_3(erf, (x))
#define erfc(x) __TGMATH_3(erfc, (x))
#define exp2(x) __TGMATH_3(exp2, (x))
#define expm1(x) __TGMATH_3(expm1, (x))
#define fdim(x, y) __TGMATH_3(fdim, (x), (y))
#define floor(x) __TGMATH_3(floor, (x))
#define fma(x, y, z) __TGMATH_3(fma, (x), (y), (z))
#define fmax(x, y) __TGMATH_3(fmax, (x), (y))
#define fmin(x, y) __TGMATH_3(fmin, (x), (y))
#define fmod(x, y) __TGMATH_3(fmod, (x), (y))
#define frexp(value, exp) __TGMATH_3(frexp, (value), (exp))
#define hypot(x, y) __TGMATH_3(hypot, (x), (y))
#define ilogb(x) __TGMATH_3(ilogb, (x))
#define ldexp(x, exp) __TGMATH_3(ldexp, (x), (exp))
#define lgamma(x) __TGMATH_3(lgamma, (x))
#define llrint(x) __TGMATH_3(llrint, (x))
#define llround(x) __TGMATH_3(llround, (x))
#define log10(x) __TGMATH_3(log10, (x))
#define log1p(x) __TGMATH_3(log1p, (x))
#define log2(x) __TGMATH_3(log2, (x))
#define logb(x) __TGMATH_3(logb, (x))
#define lrint(x) __TGMATH_3(lrint, (x))
#define lround(x) __TGMATH_3(lround, (x))
#define nearbyint(x) __TGMATH_3(nearbyint, (x))
#define nextafter(x, y) __TGMATH_3(nextafter, (x), (y))
#define nexttoward(x, y) __TGMATH_3(nexttoward, (x), (y))
#define remainder(x, y) __TGMATH_3(remainder, (x), (y))
#define remquo(x, y, quo) __TGMATH_3(remquo, (x), (y), (quo))
#define rint(x) __TGMATH_3(rint, (x))
#define round(x) __TGMATH_3(round, (x))
#define scalbn(x, n) __TGMATH_3(scalbn, (x), (n))
#define scalbln(x, n) __TGMATH_3(scalbln, (x), (n))
#define tgamma(x) __TGMATH_3(tgamma, (x))
#define trunc(x) __TGMATH_3(trunc, (x))

#define carg(z) __TGMATH_3(carg, (z))
#define cimag(z) __TGMATH_3(cimag, (z))
#define conj(z) __TGMATH_3(conj, (z))
#define cproj(z) __TGMATH_3(cproj, (z))
#define creal(z) __TGMATH_3(creal, (z))

#endif
